Try to fix clippy on darwin
Seems RPATH cannot be too long for Mach-O binaries.

```
error: install_name_tool: changing install names or rpaths can't be redone for:
/nix/store/m2h1g2zspsgmb80rmbsf138qfv0zgg2i-clippy-preview-1.59.0-beta.8-2022-02-13-x86_64-apple-darwin/bin/clippy-driver
(for architecture x86_64) because larger updated load commands do not fit
(the program must be relinked, and you may need to use -headerpad or
-headerpad_max_install_names)
```